LogDir: /tmp
Debug: false
Daemon: true
# ProxyURI:
# CAPath: /etc/ssl/certs                              # for Debian
# CAFile: /opt/local/share/curl/curl-ca-bundle.crt    # for MacPorts

Prowl:
 APIKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

NMA:
 APIKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Growl:
  Sticky: 0    # lowest priority to enable stikcy option

EXEC:
  Command: /usr/bin/aplay -B 100000 /usr/share/sounds/alsa/Front_Center.wav

Accounts:
 -
  Application: "Twitter"
  NotifyMethods:
    - "prowl" # Prowl for iPhone
#   - "nma"   # Notify My Android for Android
#   - "growl" # use growlnotify, it requires growl.gem and growlnotify
#   - "exec"  # execute command
  User: example_username
  RateLimitThreshold: 20
  UseProxy: false          # <= use Prowl::ProxyURL
  Mentions:                # Event on Mentions
    Enable: true
    Priority: 1
    IgnoreSelf: false      # Ignore mention by myself
  Direct:                  # Event on Direct Messages
    Enable: true
    Priority: 0
    IgnoreSelf: false      # Ignore DM event from myself
  Retweets:                # Event on Retweets
    Enable: true
    Priority: 0
  Membership:              # Event on List Membership
    Enable: true
    Priority: 0
    IgnoreSelf: false      # Ignore event by myself
    IgnoreNegative: false  # Ignore remove event
  Favorite:                # Event on Favorite/Unfavorite
    Enable: true
    Priority: 0
    IgnoreSelf: false      # Ignore event by myself
    IgnoreNegative: false  # Ignore Unfavorite event
  Unfollowed:              # Event on Unfollowed, requiresi API rate
    Enable: true
    Priority: 0
    Interval: 1800
  RegexpMatch:
    -
      User: "eew_jp"
      Priority: 2
      Enable: true
    -
      Text: "TwiProwl"
      Priority: 0
      Enable: true
    -
      User: "^northeye$"
      Text: "TwiProwl|twiprowl"
